# Generated by Django 5.0.1 on 2024-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
