# Generated by Django 5.0.1 on 2024-02-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='sponsor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
